language: bash
services: docker
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push chuckws09/mysql-rest-with-spring-udemy;
    docker push chuckws09/rest-with-spring-udemy;
  on:
    branch: master
notifications:
  email: false